default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: ingestor_development

test:
  <<: *default
  host: localhost
  database: ingestor_test

production:
  <<: *default
  database: ingestor_production
  username: ingestor
  password: <%= ENV['INGESTOR_DATABASE_PASSWORD'] %>
